# Generated by Django 4.2.6 on 2023-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('income', models.FloatField()),
                ('current_credit_score', models.PositiveIntegerField()),
                ('target_credit_score', models.PositiveIntegerField()),
                ('education_material_viewed', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
